### ISSUE TITLE
[REF] fork announcement on CodePlex

### ISSUE THREAD

**Issue by dtgm** [tomap/HtmlAgilityPack#1]
http://htmlagilitypack.codeplex.com/discussions/654824

> 2016-05-20 02:28:49
> Hi, 
> 
> I needed to introduce some fixes to HTMLAgilityPack 
> Especialy the one by NRenaux: 
> https://htmlagilitypack.codeplex.com/SourceControl/list/patches 
> https://www.codeplex.com/Download?ProjectName=htmlagilitypack&DownloadId=1520775 
> 
> So I made a fork 
> https://github.com/tomap/HtmlAgilityPack 
> and published a new nuget package: 
> https://www.nuget.org/packages/HtmlAgilityPack.Net45/ 
> 
> It has CI on appveyor and is compiled for .Net 4.5 only. 
> If anyone has patches to submit, I'll be glad to integrate them 
> 
> Regards, 
> 
> Thomas

**Comment by tomap** [comment]
Hi, Thank you for the reference :)
